version: "3.7"

services:
  kratos:
    container_name: kratos
    image: oryd/kratos:v1.0.0
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    restart: unless-stopped
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./config/kratos:/etc/config/kratos
    ports:
      - 4433:4433
    depends_on:
      - kratos-migrations

  kratos-migrations:
    container_name: kratos-migrations
    image: oryd/kratos:v1.0.0
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    environment:
      - DSN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./config/kratos:/etc/config/kratos

  postgres:
    container_name: postgres
    image: bitnami/postgresql:14.1.0-debian-10-r31
    restart: unless-stopped
    environment:
      - POSTGRESQL_PASSWORD=postgres
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./scripts/postgres/00-init.sql:/docker-entrypoint-initdb.d/00-init.sql
    ports:
      - 5432:5432

  mailslurper:
    container_name: mailslurper
    image: oryd/mailslurper:latest-smtps
    restart: unless-stopped
    ports:
      - 4436:4436 # ui
      - 4437:4437 # api
      - 1025:1025 # smtp

volumes:
  postgres_data:
